### ISSUE TITLE
BUG: Clicking "Device scan" button makes DSP freeze and sometimes crash

### ISSUE THREAD

**Issue by vladisslav2011** [gqrx-sdr/gqrx#1025]
Crash after clicking "Device scan" several times while the DSP is running and accepting settings with
```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
O
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOCannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.

libusb: error [udev_hotplug_event] ignoring udev action bind
gr-osmosdr 0.1.5 (0.1.5) gnuradio 3.7.11
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf rfspace airspy soapy redpitaya freesrp 
Segmentation fault (core dumped)
```
Conditions:
gqrx built from git master 49de5f35ec6bd5b835b953db030ff5acb845dfeb
Platform: Ubuntu 18.04.6 gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.11
Connected hardware: RTL2838UHIDIR + Hackrf One

Steps to reproduce:
1. Start gqrx, select HackRF start the DSP
2. Reopen "Configure I/O device" dialog
3. Do several device scans
4. Confirm device selection with "OK" button

Expected behavior:
No DSP freeze while scanning for new devices, no crash after clicking OK

Observed behavior:
Either freeze on step 3 (sometimes the DSP restart, sometimes freezes along with GUI) or crash on step 4.
Sometimes it works as expected, but repeating steps 2-4 several times always makes it crash or freeze.

Better reproduced with HackRF. May be triggered by the bug in the HackRF driver or library.

**Comment by vladisslav2011** [comment]
Backtrace:
```
Thread 1 "gqrx" received signal SIGSEGV, Segmentation fault.
0x00007fffed4b1a95 in libusb_submit_transfer () from /lib/x86_64-linux-gnu/libusb-1.0.so.0
(gdb) bt
#0  0x00007fffed4b1a95 in libusb_submit_transfer () at /lib/x86_64-linux-gnu/libusb-1.0.so.0
#1  0x00007fffed4b3ee8 in libusb_control_transfer () at /lib/x86_64-linux-gnu/libusb-1.0.so.0
#2  0x00007fffef82b973 in hackrf_set_transceiver_mode () at /usr/lib/x86_64-linux-gnu/libhackrf.so.0
#3  0x00007fffef82c31b in hackrf_stop_rx () at /usr/lib/x86_64-linux-gnu/libhackrf.so.0
#4  0x00007ffff583ed2b in  () at /usr/lib/x86_64-linux-gnu/libgnuradio-osmosdr.so.0.1.4
#5  0x00007ffff583f069 in  () at /usr/lib/x86_64-linux-gnu/libgnuradio-osmosdr.so.0.1.4
#6  0x00007ffff736aeb3 in gr::flowgraph::~flowgraph() () at /usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so.3.7.11
#7  0x00007ffff7364c39 in gr::flat_flowgraph::~flat_flowgraph() () at /usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so.3.7.11
#8  0x00007ffff73a2402 in gr::top_block_impl::start(int) () at /usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so.3.7.11
#9  0x00007ffff739dbe9 in gr::top_block::start(int) () at /usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so.3.7.11
#10 0x000055555560a94b in receiver::set_input_device(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#11 0x00005555555fc15d in MainWindow::loadConfig(QString const&, bool, bool) ()
#12 0x00005555555fd9c9 in MainWindow::on_actionIoConfig_triggered() ()
#13 0x00005555555ebc5a in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) [clone .part.50] ()
#14 0x00005555555ee0c3 in MainWindow::qt_metacall(QMetaObject::Call, int, void**) ()
#15 0x00007ffff43845e9 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff50cd122 in QAction::triggered(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff50cf80c in QAction::activate(QAction::ActionEvent) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff51c609b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff51c62fd in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff52a4fda in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff5112038 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff52a5074 in QToolButton::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff50d383c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff50db65f in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff43558a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff50da632 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff512d15b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff512f7ca in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff50d383c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff50db104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff43558a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff49175eb in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#33 0x00007ffff49190b5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#34 0x00007ffff48f033b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#35 0x00007fffe9160260 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#36 0x00007fffed70d537 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007fffed70d770 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007fffed70d7fc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff43ae85f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007ffff43538da in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007ffff435c984 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00005555555dfa35 in main ()
```
May be bug in libhackrf.

**Comment by vladisslav2011** [comment]
Yes. That's libhackrf bug and it is already fixed in current git master. Not a gqrx bug. Closing.
